engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrics/LineLength:
        enabled: false
  bundler-audit:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      - javascript:
checks:
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 100
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- test/**/*
- "**/vendor/**/*"
- bin
- client/src/semantic-ui
- config
- db
